ERROR_FAIL = 1001
ERROR_PARAM = 1002
ERROR_PW_DIFF=1003
ERROR_PW_ERROR = 1004


ERROR_ADMIN_NO_LOGIN = 2000
ERROR_NO_ADMIN = 2001

ERROR_PLAYER_NO_LOGIN = 3000
ERROR_NO_PLAYER = 3001

ERROR_NO_RESULT = 4001
ERROR_CASE_EXIST = 4002

error_info = {
    ERROR_FAIL: '操作失败',
    ERROR_PARAM: '参数错误',
    ERROR_PW_DIFF:'两次输入密码不同',

    ERROR_ADMIN_NO_LOGIN:'管理员未登录',
    ERROR_NO_ADMIN: '管理员不存在',

    ERROR_PLAYER_NO_LOGIN: '用户未登录',
    ERROR_NO_PLAYER: '用户不存在',


    ERROR_NO_RESULT: '没有查询结果',
    ERROR_CASE_EXIST:'该事件已存在，请勿重复上传',
}

